# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a181d6b1ec114aa10c55ee53b3e46a5ee93b8fef22fc21e85cf30acabef88efba200b3bae66260817914b4f2433a0ce156e9751008636c721298a0d89dfbbcd1

test:
  secret_key_base: fa776b11b3cbbddc58dea5a352bd435c214a2e0ce958b918d8b7699f2c309038828fdf9fb73f145d3af4c1fd5bbe91eece9b8313ca471f3a42235c8d39d996fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
